# Generated by Django 4.1.1 on 2022-09-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_article_dataset_alter_article_experiment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
