# Generated by Django 4.1.1 on 2022-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nas',
            field=models.TextField(blank=True),
        ),
    ]
