# Generated by Django 4.1.1 on 2022-09-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_article_nas'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='algorithm',
            field=models.TextField(blank=True),
        ),
    ]
