# Generated by Django 4.1.1 on 2022-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_article_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='architecture',
            field=models.TextField(blank=True),
        ),
    ]
