# Generated by Django 4.1.1 on 2022-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_article_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='demo',
            field=models.TextField(blank=True),
        ),
    ]
