# Generated by Django 4.1.1 on 2022-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_article_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='future',
            field=models.TextField(blank=True),
        ),
    ]
