# Generated by Django 4.1.1 on 2022-09-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('type', models.CharField(max_length=45)),
                ('temperature', models.IntegerField(blank=True)),
                ('dew_point', models.IntegerField(blank=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_gust', models.IntegerField(blank=True, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
